name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    env:
      targetZip: nasm-macos-playground-${{ github.ref_name }}.zip

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - run: ls
        working-directory: /Library/Developer/CommandLineTools/SDKs/
        
      - run: brew install nasm

      - run: nasm -v

      - run: brew install binutils

      - run: ld -v
      
      - run: nasm -f macho64 main.asm
      
      - run: ld -arch x86_64 -o main -e _start main.o -macosx_version_min 10.15

      - run: ls && ./main
      
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: main
          filename: "${{ env.targetZip }}"

      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
